---
- name: Install perl base packages
  apt:
    name: "{{ perl_base_packages }}"
    state: present

- name: Install perl optional packages
  apt:
    name: "{{ perl_optional_packages | default(omit) }}"
    state: present
  when: perl_optional_packages is defined

- name: Install CPAN modules
  cpanm:
    name: "{{ item }}"
    system_lib: yes
  with_items: "{{ perl_cpan_modules | default(omit) }}"
  when: perl_cpan_modules is defined
